### ISSUE TITLE
"exec/hello_world/main.so: undefined symbol: newArglist" on Idris2 version 0.7.0-1dc7b74e4

### ISSUE THREAD

**Issue by belonesox** [madman-bob/idris2-python#5]
Tested on FC38, FC39 with idris2 installed by idris-pack.

On `make test` got

```
  exec/hello_world/main.so: undefined symbol: newArglist" on Idris2 version 0.7.0-1dc7b74e4

    cdll.newArglist.argtypes = (ctypes.c_int, ctypes.c_int)
    ^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/ctypes/__init__.py", line 389, in __getattr__
    func = self.__getitem__(name)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/ctypes/__init__.py", line 394, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: …/idris/idris2-python/build/exec/hello_world/main.so: undefined symbol: newArglist
```

**Comment by Jademaster** [comment]
I am having the same error, but when I try to build the python module with
 ```
python -m hello_world

```
from the folder build/exec. To be precise the error is this
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/jade/idris2-python/build/exec/hello_world/__init__.py", line 12, in <module>
    cdll.newArglist.argtypes = (ctypes.c_int, ctypes.c_int)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /home/jade/idris2-python/build/exec/hello_world/main.so: undefined symbol: newArglist
```
Can you help me?

**Comment by madman-bob** [comment]
This was caused by upstream breaking changes in RefC. It should now work.
